# Project information
site_name: GenET
site_url: https://Goosang-Yu.github.io/genet/
site_author: Goosang Yu

# Repository
repo_name: genet
repo_url: https://github.com/Goosang-Yu/genet
edit_uri: ""

copyright: |
  &copy; 2023 <a href="https://github.com/Goosang-Yu" target="_blank" rel="noopener">Goosang Yu</a>

theme:
  name: material
  custom_dir: docs/en/overrides

  # 404 page
  static_templates:
    - 404.html

  language: en
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.share
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate
  

  font:
    text: Roboto
    code: Roboto Mono
  
  logo: assets/images/logo.png

  # icon:
    # logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#   - blog

# Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py



extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Goosang-Yu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Goosang_Yu

  analytics:
    provider: google
    property: G-NT7P9BPR1Y

  # Site language selector
  # alternate:
  #   - name: Korean
  #     link: ../ko/
  #     lang: ko

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  # - pymdownx.inlinebilite ##??? Why not imported?
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


docs_dir: docs/en

# Page tree
nav:
  - Home: README.md
  - Getting started:
    - Getting started: getting_started.md
    - Introduction: introduction.md
    - Installation: installation.md
  
  - Predict:
    - How it works: 1_Predict/1_howworks.md
    - Cas9 nuclease: 1_Predict/2_predict_cas9.md
    - Base editor: 1_Predict/3_predict_be.md
    - Prime editor: 1_Predict/4_predict_pe.md

  - Design:
    - Genet design module: 2_Design/1_Design_intro.md
    - Synonymous PE: 2_Design/2_SynonymousPE.md
  
  - Database:
    - Genet database module: 3_Database/1_database_intro.md
    - Background  : 3_Database/2_Genome_resource_background.md
    - Metadata    : 3_Database/3_Metadata from databases.md
    - Download    : 3_Database/4_Download_files.md

  - Analysis:
    - Genet Analysis module: 4_Analysis/1_analysis_intro.md
  
  - Utils:
    - Genet Utils module: 5_Utils/1_utils_intro.md
    - Download from server: 5_Utils/2_download_files.md

  - Application note:
    - Genome-wide KO lIbrary: 6_Application_notes/Genome-wide_KO_library.md